mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # 自动转换下划线命名到驼峰命名
pagehelper:
  helper-dialect: mysql  # 根据实际数据库类型配置
  reasonable: true       # 分页参数合理化（pageNum<=0时自动设为1）
  support-methods-arguments: true
  close-conn: true        # 自动关闭Connection
spring:
  application:
    name: wot-style-blog-server
  datasource:
    url: jdbc:mysql://localhost:3306/wot-style-blog?useSSL=false
    username: root
    password: cxxh19981014
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9093
nasa:
  api:
    key: sNix0tvOuyS2t64DKEvnYaVrQ7I0ARgfUByIHP3j
rsa:
  privateKey:
    value: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGHh64wPlqxWLfV7ZMBE7YezVvZja+YsqQU2n57V7uuSJ5edukQlxwLmS4RKXdjkDuxuOqukaltcRefg7ZWnnor92iJe9rN8xnS9MIl1tz5JsTNZTvWsJk1FID+ls8LewMyuV1m88YKtnRSGdHT7591urZG892x8g7ABxor0N7cT33g5hKotzj1LHzrBv/RmWE5a+ARefcBw5KotrIgYrHAD6/M6tFICdei6otSF0Ee/DM2YDVO6HSJYw3IbH/6hEGmNw7OSuZt7ZnwDrPlIyXdtnCl3GY3ZMZAlK07SGZmuQc1x/yuC5UlNWUZW3z6uKk63sfCe9PphWtxavB4oIPAgMBAAECggEAHQpUOYO76700QYXDaIAnKI9i5Unn0196zs4TVjnHtRl5JrJIklrR3vXF+MbDQ2czOGz5+VAlw+uRdcJnnc+n2AZTaA3EewRqV2fjbrp1AtdrLdUoWC+HGC2ROhkMH5WhqLxjByrIIARD+mvxC6ByTVLgCOQNNJ2TSaa6A1RRgXn1Y7MGzrOUF2SfDShOGKW/poBAlGvGinpf0dulOdGsGA0GG/VII9UEHm0azAIgUpIoCdFZLbA0ZgbyXzkUcPVoY+JCrkbx+UG2b21mgqlLgA8toOsPY60K7C6j29YP/kjm0s9JVaUDXZGMqno/ArEGRioBheWbY08z9S2sJXa0PQKBgQDrSutPXbfABE9/uhqbHKzZCT/wjRzh7VVuIFSN3al8ZJbT/8MFVTCd3uFyhjkxBeMOh1qMZ8N7Lob50MTVXy2Yt43HkAojqVO5348DyGerAFb5Arq5TpICjZdj6rPLCok0e2+MgcDL7nhsAVwP59HbORGoZBiUsvNKssOnaayQXQKBgQDXjah13L7ogmQZnuq6x9Jy7wMNzGrAxcAgvRnJgCivFT9f4CrdvIa+IZpGi9AnAYdz6CmBjsiB7l94esN3zUG6/Tpd847aT6ryVc3YCZDIWDqgzbN8fAKO34F59oeHnBb5EYaXUgtv674mZHhwbFM0L5qsnKqe9GjxQ7BDf4jlWwKBgQCY2ayPfGQ4GxTB9tX92dz3iSi+Tg1rP1B2IA6Nsme95WKOCeJY/oR8qiNu0H8qt5ZPA+Lwvx+gUBNjCho0OoZWZTd3Yr0TeZZoczBm1rNxxOC7FujSJJZ5jh3AzOFLj2aeb2mBr3Ddiec00pVJx+DuNt6fs5a8Upv19LdhdCakCQKBgQDAuIvszS/3LFWZPqe51dzIHACL/r9XmbbczpXWvfoiCApAi2loFR4Xsm2AM5MovMpBjEpH5sRIvzqmuoQ3gdIKAEyGIbQQZnh98M95H5xOM+w/R4r5etrCqPzXcd7dFWbIy62db6KAL7M0GlJAmemOWB2fxPcb5YRKae2Xe9iGzwKBgHv2VYbCOBLtcOTINnsiEPcxuqOrCW5yp8Q30A+m9vbeqVtXk0UVewTUSvfVkWMLyplzdkeRq1D+wQ4Li9xSmIqyPeiR9iHMqLtMspFT52pleYfrZUh2EZsYGJA2brd8+Jk734AkkViQ3VnQudEohswMaAkz506iRieG/+uzP/bN"
